sbsigntool-native: fix the segment fault caused by the uninitialized sigbuf
This patch resolves the following failure during the build:
ERROR: Function failed: ERROR: Unable to sign /buildarea1/jhu2/plusar8/wr-core/build-advantech-utx-3117/tmp/work/core2-64-wrs-linux/grub-efi/2.00-r3.fix0/image/boot/efi/EFI/BOOT/grubx64.efi

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>